/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorScheduleRouteImport } from './routes/doctor/schedule'
import { Route as DoctorProfileRouteImport } from './routes/doctor/profile'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorKycRouteImport } from './routes/doctor/kyc'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorConsultationsRouteImport } from './routes/doctor/consultations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPharmacyRouteImport } from './routes/admin/pharmacy'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAmbulanceRouteImport } from './routes/admin/ambulance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedPharmacyIndexRouteImport } from './routes/_authenticated/pharmacy.index'
import { Route as AuthenticatedEmergencyIndexRouteImport } from './routes/_authenticated/emergency.index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors.index'
import { Route as AuthenticatedConsultationsIndexRouteImport } from './routes/_authenticated/consultations.index'
import { Route as DoctorConsultationsIdRouteImport } from './routes/doctor/consultations.$id'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'
import { Route as AdminDoctorsUserIdRouteImport } from './routes/admin/doctors.$userId'
import { Route as AuthenticatedPharmacyOrdersRouteImport } from './routes/_authenticated/pharmacy.orders'
import { Route as AuthenticatedPharmacyCartRouteImport } from './routes/_authenticated/pharmacy.cart'
import { Route as AuthenticatedDoctorsIdRouteImport } from './routes/_authenticated/doctors.$id'
import { Route as AuthenticatedConsultationsIdRouteImport } from './routes/_authenticated/consultations.$id'
import { Route as AuthenticatedBookDoctorIdRouteImport } from './routes/_authenticated/book.$doctorId'
import { Route as AuthenticatedEmergencyConfirmedIdRouteImport } from './routes/_authenticated/emergency.confirmed.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorKycRoute = DoctorKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorConsultationsRoute = DoctorConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPharmacyRoute = AdminPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbulanceRoute = AdminAmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyIndexRoute =
  AuthenticatedPharmacyIndexRouteImport.update({
    id: '/pharmacy/',
    path: '/pharmacy/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmergencyIndexRoute =
  AuthenticatedEmergencyIndexRouteImport.update({
    id: '/emergency/',
    path: '/emergency/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsultationsIndexRoute =
  AuthenticatedConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DoctorConsultationsIdRoute = DoctorConsultationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorConsultationsRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDoctorsUserIdRoute = AdminDoctorsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminDoctorsRoute,
} as any)
const AuthenticatedPharmacyOrdersRoute =
  AuthenticatedPharmacyOrdersRouteImport.update({
    id: '/pharmacy/orders',
    path: '/pharmacy/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyCartRoute =
  AuthenticatedPharmacyCartRouteImport.update({
    id: '/pharmacy/cart',
    path: '/pharmacy/cart',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoctorsIdRoute = AuthenticatedDoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsultationsIdRoute =
  AuthenticatedConsultationsIdRouteImport.update({
    id: '/consultations/$id',
    path: '/consultations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookDoctorIdRoute =
  AuthenticatedBookDoctorIdRouteImport.update({
    id: '/book/$doctorId',
    path: '/book/$doctorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmergencyConfirmedIdRoute =
  AuthenticatedEmergencyConfirmedIdRouteImport.update({
    id: '/emergency/confirmed/$id',
    path: '/emergency/confirmed/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/ambulance': typeof AdminAmbulanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteWithChildren
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/kyc': typeof DoctorKycRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/pharmacy/cart': typeof AuthenticatedPharmacyCartRoute
  '/pharmacy/orders': typeof AuthenticatedPharmacyOrdersRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/emergency/': typeof AuthenticatedEmergencyIndexRoute
  '/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/emergency/confirmed/$id': typeof AuthenticatedEmergencyConfirmedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/ambulance': typeof AdminAmbulanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteWithChildren
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/kyc': typeof DoctorKycRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/pharmacy/cart': typeof AuthenticatedPharmacyCartRoute
  '/pharmacy/orders': typeof AuthenticatedPharmacyOrdersRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/consultations': typeof AuthenticatedConsultationsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/emergency': typeof AuthenticatedEmergencyIndexRoute
  '/pharmacy': typeof AuthenticatedPharmacyIndexRoute
  '/emergency/confirmed/$id': typeof AuthenticatedEmergencyConfirmedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/ambulance': typeof AdminAmbulanceRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/doctors': typeof AdminDoctorsRouteWithChildren
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRouteWithChildren
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/kyc': typeof DoctorKycRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/_authenticated/book/$doctorId': typeof AuthenticatedBookDoctorIdRoute
  '/_authenticated/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/_authenticated/doctors/$id': typeof AuthenticatedDoctorsIdRoute
  '/_authenticated/pharmacy/cart': typeof AuthenticatedPharmacyCartRoute
  '/_authenticated/pharmacy/orders': typeof AuthenticatedPharmacyOrdersRoute
  '/admin/doctors/$userId': typeof AdminDoctorsUserIdRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/_authenticated/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/emergency/': typeof AuthenticatedEmergencyIndexRoute
  '/_authenticated/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
  '/_authenticated/emergency/confirmed/$id': typeof AuthenticatedEmergencyConfirmedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/appointments'
    | '/home'
    | '/notifications'
    | '/prescriptions'
    | '/profile'
    | '/admin/ambulance'
    | '/admin/banners'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/pharmacy'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/dashboard'
    | '/doctor/kyc'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/book/$doctorId'
    | '/consultations/$id'
    | '/doctors/$id'
    | '/pharmacy/cart'
    | '/pharmacy/orders'
    | '/admin/doctors/$userId'
    | '/api/public/flutterwave-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/push-dispatch'
    | '/api/public/stripe-webhook'
    | '/doctor/consultations/$id'
    | '/consultations/'
    | '/doctors/'
    | '/emergency/'
    | '/pharmacy/'
    | '/emergency/confirmed/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/appointments'
    | '/home'
    | '/notifications'
    | '/prescriptions'
    | '/profile'
    | '/admin/ambulance'
    | '/admin/banners'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/pharmacy'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/dashboard'
    | '/doctor/kyc'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/book/$doctorId'
    | '/consultations/$id'
    | '/doctors/$id'
    | '/pharmacy/cart'
    | '/pharmacy/orders'
    | '/admin/doctors/$userId'
    | '/api/public/flutterwave-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/push-dispatch'
    | '/api/public/stripe-webhook'
    | '/doctor/consultations/$id'
    | '/consultations'
    | '/doctors'
    | '/emergency'
    | '/pharmacy'
    | '/emergency/confirmed/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/doctor'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/appointments'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/prescriptions'
    | '/_authenticated/profile'
    | '/admin/ambulance'
    | '/admin/banners'
    | '/admin/doctors'
    | '/admin/overview'
    | '/admin/pharmacy'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/dashboard'
    | '/doctor/kyc'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/_authenticated/book/$doctorId'
    | '/_authenticated/consultations/$id'
    | '/_authenticated/doctors/$id'
    | '/_authenticated/pharmacy/cart'
    | '/_authenticated/pharmacy/orders'
    | '/admin/doctors/$userId'
    | '/api/public/flutterwave-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/push-dispatch'
    | '/api/public/stripe-webhook'
    | '/doctor/consultations/$id'
    | '/_authenticated/consultations/'
    | '/_authenticated/doctors/'
    | '/_authenticated/emergency/'
    | '/_authenticated/pharmacy/'
    | '/_authenticated/emergency/confirmed/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/kyc': {
      id: '/doctor/kyc'
      path: '/kyc'
      fullPath: '/doctor/kyc'
      preLoaderRoute: typeof DoctorKycRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/consultations': {
      id: '/doctor/consultations'
      path: '/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof DoctorConsultationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pharmacy': {
      id: '/admin/pharmacy'
      path: '/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AdminPharmacyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ambulance': {
      id: '/admin/ambulance'
      path: '/ambulance'
      fullPath: '/admin/ambulance'
      preLoaderRoute: typeof AdminAmbulanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/': {
      id: '/_authenticated/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AuthenticatedPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency/': {
      id: '/_authenticated/emergency/'
      path: '/emergency'
      fullPath: '/emergency/'
      preLoaderRoute: typeof AuthenticatedEmergencyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultations/': {
      id: '/_authenticated/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AuthenticatedConsultationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/doctor/consultations/$id': {
      id: '/doctor/consultations/$id'
      path: '/$id'
      fullPath: '/doctor/consultations/$id'
      preLoaderRoute: typeof DoctorConsultationsIdRouteImport
      parentRoute: typeof DoctorConsultationsRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors/$userId': {
      id: '/admin/doctors/$userId'
      path: '/$userId'
      fullPath: '/admin/doctors/$userId'
      preLoaderRoute: typeof AdminDoctorsUserIdRouteImport
      parentRoute: typeof AdminDoctorsRoute
    }
    '/_authenticated/pharmacy/orders': {
      id: '/_authenticated/pharmacy/orders'
      path: '/pharmacy/orders'
      fullPath: '/pharmacy/orders'
      preLoaderRoute: typeof AuthenticatedPharmacyOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/cart': {
      id: '/_authenticated/pharmacy/cart'
      path: '/pharmacy/cart'
      fullPath: '/pharmacy/cart'
      preLoaderRoute: typeof AuthenticatedPharmacyCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors/$id': {
      id: '/_authenticated/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof AuthenticatedDoctorsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consultations/$id': {
      id: '/_authenticated/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof AuthenticatedConsultationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book/$doctorId': {
      id: '/_authenticated/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof AuthenticatedBookDoctorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency/confirmed/$id': {
      id: '/_authenticated/emergency/confirmed/$id'
      path: '/emergency/confirmed/$id'
      fullPath: '/emergency/confirmed/$id'
      preLoaderRoute: typeof AuthenticatedEmergencyConfirmedIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookDoctorIdRoute: typeof AuthenticatedBookDoctorIdRoute
  AuthenticatedConsultationsIdRoute: typeof AuthenticatedConsultationsIdRoute
  AuthenticatedDoctorsIdRoute: typeof AuthenticatedDoctorsIdRoute
  AuthenticatedPharmacyCartRoute: typeof AuthenticatedPharmacyCartRoute
  AuthenticatedPharmacyOrdersRoute: typeof AuthenticatedPharmacyOrdersRoute
  AuthenticatedConsultationsIndexRoute: typeof AuthenticatedConsultationsIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedEmergencyIndexRoute: typeof AuthenticatedEmergencyIndexRoute
  AuthenticatedPharmacyIndexRoute: typeof AuthenticatedPharmacyIndexRoute
  AuthenticatedEmergencyConfirmedIdRoute: typeof AuthenticatedEmergencyConfirmedIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookDoctorIdRoute: AuthenticatedBookDoctorIdRoute,
  AuthenticatedConsultationsIdRoute: AuthenticatedConsultationsIdRoute,
  AuthenticatedDoctorsIdRoute: AuthenticatedDoctorsIdRoute,
  AuthenticatedPharmacyCartRoute: AuthenticatedPharmacyCartRoute,
  AuthenticatedPharmacyOrdersRoute: AuthenticatedPharmacyOrdersRoute,
  AuthenticatedConsultationsIndexRoute: AuthenticatedConsultationsIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedEmergencyIndexRoute: AuthenticatedEmergencyIndexRoute,
  AuthenticatedPharmacyIndexRoute: AuthenticatedPharmacyIndexRoute,
  AuthenticatedEmergencyConfirmedIdRoute:
    AuthenticatedEmergencyConfirmedIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminDoctorsRouteChildren {
  AdminDoctorsUserIdRoute: typeof AdminDoctorsUserIdRoute
}

const AdminDoctorsRouteChildren: AdminDoctorsRouteChildren = {
  AdminDoctorsUserIdRoute: AdminDoctorsUserIdRoute,
}

const AdminDoctorsRouteWithChildren = AdminDoctorsRoute._addFileChildren(
  AdminDoctorsRouteChildren,
)

interface AdminRouteChildren {
  AdminAmbulanceRoute: typeof AdminAmbulanceRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDoctorsRoute: typeof AdminDoctorsRouteWithChildren
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPharmacyRoute: typeof AdminPharmacyRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAmbulanceRoute: AdminAmbulanceRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminDoctorsRoute: AdminDoctorsRouteWithChildren,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPharmacyRoute: AdminPharmacyRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorConsultationsRouteChildren {
  DoctorConsultationsIdRoute: typeof DoctorConsultationsIdRoute
}

const DoctorConsultationsRouteChildren: DoctorConsultationsRouteChildren = {
  DoctorConsultationsIdRoute: DoctorConsultationsIdRoute,
}

const DoctorConsultationsRouteWithChildren =
  DoctorConsultationsRoute._addFileChildren(DoctorConsultationsRouteChildren)

interface DoctorRouteChildren {
  DoctorConsultationsRoute: typeof DoctorConsultationsRouteWithChildren
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorKycRoute: typeof DoctorKycRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorConsultationsRoute: DoctorConsultationsRouteWithChildren,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorKycRoute: DoctorKycRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
